//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSheet()
        {
            this.tblSheetStatus = new HashSet<tblSheetStatu>();
            this.tblTasks = new HashSet<tblTask>();
        }
    
        public int ID { get; set; }
        public string userID { get; set; }
        public string weekNo { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public string createdByID { get; set; }
        public Nullable<System.DateTime> updationDate { get; set; }
        public string updatedByID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSheetStatu> tblSheetStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTask> tblTasks { get; set; }
    }
}
