//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaskStatu
    {
        public int ID { get; set; }
        public Nullable<int> taskID { get; set; }
        public Nullable<int> statusID { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public string createdByID { get; set; }
        public Nullable<System.DateTime> updationDate { get; set; }
        public string updatedByID { get; set; }
    
        public virtual tblLookUp tblLookUp { get; set; }
        public virtual tblTask tblTask { get; set; }
    }
}
